<?php
declare(strict_types=1);

namespace JTarleton\Sprig;

/**
 * Compiler
 * --------
 * Walks the Node tree and emits PHP source code as a string.
 *
 * The output is a class extending Sprig\Template with a single
 * doDisplay(array $context) method. Real Twig writes this class to a
 * cache directory and `require`s it on subsequent renders; here we just
 * eval() it (see Environment::load).
 *
 * The Compiler only manages output (the buffer + indent level).
 * Each Node decides what PHP to emit. That separation is what makes
 * Twig extensible — to add a new tag in real Twig you just write a
 * new Node class with its own compile() method.
 */
final class Compiler
{
    private string $source = '';
    private int $indent = 0;

    /** Compile a full module to a complete PHP class definition. */
    public function compile(Node $node, string $className): string
    {
        $this->source = '';
        // Statements inside doDisplay() should sit at 8 spaces (= indent 2).
        $this->indent = 2;
        $node->compile($this);

        return "<?php\n"
             . "// Auto-generated by JTarleton\\Sprig — do not edit.\n"
             . "class {$className} extends \\JTarleton\\Sprig\\Template\n"
             . "{\n"
             . "    protected function doDisplay(array \$context): void\n"
             . "    {\n"
             . $this->source
             . "    }\n"
             . "}\n";
    }

    public function raw(string $s): self
    {
        $this->source .= $s;
        return $this;
    }

    /** Emit a PHP literal (string, int, bool, null, array, ...). */
    public function repr(mixed $v): self
    {
        $this->source .= var_export($v, true);
        return $this;
    }

    public function writeIndent(): self
    {
        $this->source .= str_repeat(' ', $this->indent * 4);
        return $this;
    }

    public function indent(): self
    {
        $this->indent++;
        return $this;
    }

    public function outdent(): self
    {
        $this->indent--;
        return $this;
    }
}
